# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window_Calendario.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calendario(object):
    def setupUi(self, Calendario):
        Calendario.setObjectName("Calendario")
        Calendario.resize(1001, 889)
        self.calendarWidget = QtWidgets.QCalendarWidget(Calendario)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 10, 481, 301))
        self.calendarWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName("calendarWidget")
        self.groupBox = QtWidgets.QGroupBox(Calendario)
        self.groupBox.setGeometry(QtCore.QRect(520, 10, 461, 301))
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(20, 21, 421, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.groupBox_2 = QtWidgets.QGroupBox(Calendario)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 320, 461, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 20, 421, 241))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.groupBox_3 = QtWidgets.QGroupBox(Calendario)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 320, 481, 271))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 481, 271))
        self.groupBox_4.setObjectName("groupBox_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget_3.setGeometry(QtCore.QRect(20, 20, 441, 241))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.groupBox_5 = QtWidgets.QGroupBox(Calendario)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 600, 481, 271))
        self.groupBox_5.setObjectName("groupBox_5")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableWidget_4.setGeometry(QtCore.QRect(20, 20, 441, 241))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Calendario)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(800, 690, 181, 181))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_2)
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.gridLayout_2.addWidget(self.commandLinkButton_3, 2, 0, 1, 1)
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_2)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.gridLayout_2.addWidget(self.commandLinkButton_2, 3, 0, 1, 1)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_2)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.gridLayout_2.addWidget(self.commandLinkButton, 4, 0, 1, 1)
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_2)
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.gridLayout_2.addWidget(self.commandLinkButton_4, 1, 0, 1, 1)

        self.retranslateUi(Calendario)
        QtCore.QMetaObject.connectSlotsByName(Calendario)

    def retranslateUi(self, Calendario):
        _translate = QtCore.QCoreApplication.translate
        Calendario.setWindowTitle(_translate("Calendario", "Dialog"))
        self.groupBox.setTitle(_translate("Calendario", "Dividendos Confirmados"))
        self.groupBox_2.setTitle(_translate("Calendario", "Dividendos Esperados"))
        self.groupBox_3.setTitle(_translate("Calendario", "Sugestão de Compra"))
        self.groupBox_4.setTitle(_translate("Calendario", "Sugestão de Compra"))
        self.groupBox_5.setTitle(_translate("Calendario", "Sugestão de Venda"))
        self.commandLinkButton_3.setText(_translate("Calendario", "Window Gráficos"))
        self.commandLinkButton_2.setText(_translate("Calendario", "Window Dividendos"))
        self.commandLinkButton.setText(_translate("Calendario", "Window Analise"))
        self.commandLinkButton_4.setText(_translate("Calendario", "Window Ordens"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calendario = QtWidgets.QDialog()
    ui = Ui_Calendario()
    ui.setupUi(Calendario)
    Calendario.show()
    sys.exit(app.exec_())
