# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window_Modos.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Modos(object):
    def setupUi(self, Modos):
        Modos.setObjectName("Modos")
        Modos.resize(400, 116)
        self.groupBox = QtWidgets.QGroupBox(Modos)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 121, 91))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 91, 54))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.groupBox_2 = QtWidgets.QGroupBox(Modos)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 10, 221, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-40, 20, 251, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)

        self.retranslateUi(Modos)
        QtCore.QMetaObject.connectSlotsByName(Modos)

    def retranslateUi(self, Modos):
        _translate = QtCore.QCoreApplication.translate
        Modos.setWindowTitle(_translate("Modos", "Modos"))
        self.groupBox.setTitle(_translate("Modos", "Automático"))
        self.pushButton.setText(_translate("Modos", "Iniciar"))
        self.pushButton_2.setText(_translate("Modos", "Parar"))
        self.groupBox_2.setTitle(_translate("Modos", "Status"))
        self.label.setText(_translate("Modos", "Status:"))
        self.label_4.setText(_translate("Modos", "Carregando..."))
        self.label_2.setText(_translate("Modos", "Manual"))
        self.label_3.setText(_translate("Modos", "Data/Hora:"))
        self.label_5.setText(_translate("Modos", "Método Atual:"))
        self.label_6.setText(_translate("Modos", "Carregando..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Modos = QtWidgets.QDialog()
    ui = Ui_Modos()
    ui.setupUi(Modos)
    Modos.show()
    sys.exit(app.exec_())
