# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window_Ordens.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_Ordens(object):
    def setupUi(self, Window_Ordens):
        Window_Ordens.setObjectName("Window_Ordens")
        Window_Ordens.resize(1234, 808)
        self.label = QtWidgets.QLabel(Window_Ordens)
        self.label.setGeometry(QtCore.QRect(970, 60, 221, 351))
        self.label.setText("")
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(Window_Ordens)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1241, 811))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton = QtWidgets.QPushButton(self.tab_4)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 0, 811, 92))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(120, 110, 791, 601))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(950, 10, 251, 391))
        self.groupBox.setObjectName("groupBox")
        self.groupBox.raise_()
        self.pushButton.raise_()
        self.verticalLayoutWidget.raise_()
        self.label_2.raise_()
        self.tabWidget.addTab(self.tab_4, "")
        self.tabWidget.raise_()
        self.label.raise_()

        self.retranslateUi(Window_Ordens)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Window_Ordens)

    def retranslateUi(self, Window_Ordens):
        _translate = QtCore.QCoreApplication.translate
        Window_Ordens.setWindowTitle(_translate("Window_Ordens", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Window_Ordens", "Criar Ordem"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Window_Ordens", "Listar Ordens"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Window_Ordens", "Excluir Ordem"))
        self.pushButton.setText(_translate("Window_Ordens", "Verificar"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Window_Ordens", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Window_Ordens", "Extensão"))
        self.groupBox.setTitle(_translate("Window_Ordens", "Texto da Imagem"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Window_Ordens", "Verificar Notas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_Ordens = QtWidgets.QDialog()
    ui = Ui_Window_Ordens()
    ui.setupUi(Window_Ordens)
    Window_Ordens.show()
    sys.exit(app.exec_())
