# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window_Graficos.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_Graficos(object):
    def setupUi(self, Window_Graficos):
        Window_Graficos.setObjectName("Window_Graficos")
        Window_Graficos.resize(797, 542)
        self.tabWidget = QtWidgets.QTabWidget(Window_Graficos)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 801, 451))
        self.groupBox.setObjectName("groupBox")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView.setGeometry(QtCore.QRect(10, 160, 781, 281))
        self.graphicsView.setObjectName("graphicsView")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_2.setGeometry(QtCore.QRect(10, 90, 81, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.label_2.setObjectName("label_2")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(10, 40, 81, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 130, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 20, 201, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 160, 160))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.verticalLayout.addWidget(self.dateEdit_3)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.dateEdit_4 = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.verticalLayout.addWidget(self.dateEdit_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Window_Graficos)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Window_Graficos)

    def retranslateUi(self, Window_Graficos):
        _translate = QtCore.QCoreApplication.translate
        Window_Graficos.setWindowTitle(_translate("Window_Graficos", "Dialog"))
        self.groupBox.setTitle(_translate("Window_Graficos", "Dividendos"))
        self.label_2.setText(_translate("Window_Graficos", "Data Final"))
        self.label.setText(_translate("Window_Graficos", "Data Inicial"))
        self.pushButton.setText(_translate("Window_Graficos", "Exibir Gráfico"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Window_Graficos", "Somátoria de Dividendos por Período"))
        self.groupBox_2.setTitle(_translate("Window_Graficos", "Dados da Ação"))
        self.label_3.setText(_translate("Window_Graficos", "Simbolo"))
        self.lineEdit.setPlaceholderText(_translate("Window_Graficos", "Digite aqui"))
        self.label_4.setText(_translate("Window_Graficos", "1° Data Ex"))
        self.label_5.setText(_translate("Window_Graficos", "2° Data Ex"))
        self.pushButton_2.setText(_translate("Window_Graficos", "Plotar Gráfico"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Window_Graficos", "Analise Gráfica Entre Data Ex"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_Graficos = QtWidgets.QDialog()
    ui = Ui_Window_Graficos()
    ui.setupUi(Window_Graficos)
    Window_Graficos.show()
    sys.exit(app.exec_())
